[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Add card mult localization
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''elseif _c.set == 'Enhanced' then'''
position = "before"
payload = '''
    if specific_vars and specific_vars.bonus_mult then
        localize { type = 'other', key = 'card_extra_mult', nodes = desc_nodes, vars = { specific_vars.bonus_mult } }
    end
'''
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''bonus_chips = (self.ability.bonus + (self.ability.perma_bonus or 0)) > 0 and (self.ability.bonus + (self.ability.perma_bonus or 0)) or nil,'''
position = "after"
payload = '''
bonus_mult = (self.ability.mult + (self.ability.perma_mult or 0)) > 0 and (self.ability.mult + (self.ability.perma_mult or 0)) or nil
'''
match_indent = true
overwrite = false
